import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  scrollContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingBottom: 0,
  },
  headerBlock: {
    paddingBottom: 8,
  },
  calendarArea: {
    flex: 1,
  },
  monthPager: {
    flex: 1,
  },
  monthGrid: {
    flex: 1,
  },
  headerRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  monthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  monthText: {
    fontSize: 28,
    fontWeight: '600',
    color: '#1b1b1b',
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 14,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#1b1b1b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  employeeRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  employeeLabel: {
    fontSize: 15,
    color: '#8b8b8b',
    fontWeight: '600',
  },
  employeeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e7e7e7',
    backgroundColor: '#ffffff',
  },
  employeeName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1b1b1b',
  },
  weekRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flex: 1,
    paddingTop: 6,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
  },
  dayCell: {
    flex: 1,
    paddingHorizontal: 2,
    height: '100%',
  },
  dayHeader: {
    alignItems: 'center',
    marginBottom: 4,
  },
  dayNumberWrapper: {
    width: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayNumber: {
    fontSize: 13,
    color: '#1b1b1b',
  },
  dayNumberMuted: {
    color: '#bdbdbd',
  },
  dayNumberSunday: {
    color: '#e04b4b',
  },
  selectedDayCircle: {
    borderRadius: 13,
    backgroundColor: '#333333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayNumberSelected: {
    color: '#ffffff',
    fontWeight: '700',
  },
  eventStack: {
    gap: 4,
  },
  eventPill: {
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  eventText: {
    fontSize: 10,
    fontWeight: '600',
  },
  morePill: {
    alignSelf: 'flex-start',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: '#f0f0f0',
  },
  moreText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6f6f6f',
  },
  weekPager: {
    flex: 1,
  },
  weekAgendaPage: {
    justifyContent: 'space-between',
  },
  weekAgendaDay: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#ebebeb',
    paddingVertical: 6,
  },
  weekAgendaDateCol: {
    width: 86,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekAgendaDate: {
    fontSize: 34,
    lineHeight: 36,
    fontWeight: '700',
    color: '#1b1b1b',
  },
  weekAgendaWeekday: {
    marginTop: 2,
    fontSize: 11,
    color: '#8b8b8b',
    textTransform: 'capitalize',
  },
  weekAgendaEvents: {
    flex: 1,
    maxHeight: '100%',
    paddingRight: 8,
  },
  weekAgendaEventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  weekAgendaColorBar: {
    width: 4,
    height: 16,
    borderRadius: 2,
    marginRight: 6,
  },
  weekAgendaTime: {
    width: 44,
    fontSize: 11,
    lineHeight: 13,
    marginRight: 2,
    fontWeight: '600',
  },
  weekAgendaTitle: {
    flexShrink: 1,
    fontSize: 11,
    lineHeight: 13,
    color: '#1f1f1f',
    fontWeight: '600',
    marginRight: 2,
  },
  listContent: {
    paddingTop: 4,
    paddingBottom: 120,
  },
  listLoadingFooter: {
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listFullBleed: {
    marginHorizontal: -16,
  },
  listStickyHeader: {
    backgroundColor: '#fbfbfb',
    borderTopWidth: 1,
    borderTopColor: '#ececec',
    borderBottomWidth: 1,
    borderBottomColor: '#ececec',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  listStickyTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1b1b1b',
  },
  listStickyToday: {
    fontSize: 13,
    fontWeight: '600',
    color: '#8b8b8b',
  },
  listEventRow: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#efefef',
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  listEventTimeCol: {
    width: 48,
    marginRight: 6,
  },
  listEventTime: {
    fontSize: 12,
    fontWeight: '600',
  },
  listEventTimeMuted: {
    marginTop: 1,
    fontSize: 10,
    color: '#9a9a9a',
  },
  listEventBar: {
    width: 3,
    height: 36,
    borderRadius: 2,
    marginRight: 8,
  },
  listEventTextCol: {
    flex: 1,
  },
  listEventTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1f1f1f',
  },
  listEventSubtitle: {
    marginTop: 1,
    fontSize: 11,
    color: '#8b8b8b',
  },
  listEventAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#d8cfc6',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
  },
  listEventAvatarText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#4a4a4a',
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  sheetCard: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
    minHeight: 420,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 52,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#d9d9d9',
    marginBottom: 12,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1b1b1b',
  },
  sheetSubtitle: {
    fontSize: 14,
    color: '#8b8b8b',
    marginTop: 2,
  },
  sheetAddButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1b1b1b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetList: {
    gap: 14,
  },
  sheetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sheetLine: {
    width: 3,
    height: 40,
    borderRadius: 2,
  },
  sheetRowContent: {
    width: 56,
  },
  sheetTime: {
    fontSize: 14,
    color: '#1b1b1b',
  },
  sheetTimeMuted: {
    fontSize: 12,
    color: '#8b8b8b',
  },
  sheetEventText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1b1b1b',
  },
  sheetEventSubtitle: {
    marginTop: 2,
    fontSize: 13,
    color: '#8b8b8b',
  },
  sheetCheckoutButton: {
    marginLeft: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e7e7e7',
  },
  menuOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  modeMenu: {
    position: 'absolute',
    bottom: 16,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  modeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
  },
  modeItemActive: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
  },
  modeText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#1b1b1b',
  },
  stateContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 32,
  },
  stateText: {
    fontSize: 15,
    color: '#8b8b8b',
    textAlign: 'center',
  },
  retryButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#1b1b1b',
  },
  retryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
  errorBanner: {
    marginTop: 8,
    marginBottom: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#fdecea',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  errorBannerText: {
    flex: 1,
    fontSize: 13,
    color: '#c0392b',
  },
  errorBannerRetry: {
    fontSize: 13,
    fontWeight: '700',
    color: '#c0392b',
  },
  staffMenu: {
    position: 'absolute',
    top: 90,
    right: 16,
    minWidth: 200,
    maxHeight: 320,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingVertical: 6,
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  staffMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  staffMenuAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#d8cfc6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  staffMenuName: {
    flex: 1,
    fontSize: 15,
    color: '#1b1b1b',
  },
  fab: {
    position: 'absolute',
    right: 18,
    bottom: 16,
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
});
