import { StyleSheet } from 'react-native';

import { Colors } from '@/constants/theme';

export const createStyles = (theme: typeof Colors.light) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContent: {
      flex: 1,
      paddingHorizontal: 16,
      paddingBottom: 0,
    },
    headerBlock: {
      paddingBottom: 4,
    },
    calendarArea: {
      flex: 1,
    },
    monthPager: {
      flex: 1,
    },
    monthGrid: {
      flex: 1,
    },
    // Single row: month title (tap → jump to today) · employee filter chip ·
    // add + view-mode buttons. Was two rows with a redundant "Employee"
    // label; collapsing it reclaims height for the calendar grid, which is
    // what actually matters now that the tab bar floats over the last row.
    headerRow: {
      marginTop: 6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    monthRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      flexShrink: 0,
    },
    monthText: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.text,
    },
    headerIcons: {
      flexDirection: 'row',
      gap: 8,
      marginLeft: 'auto',
    },
    iconButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.text,
      alignItems: 'center',
      justifyContent: 'center',
    },
    employeeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.background,
      flexShrink: 1,
      minWidth: 0,
    },
    employeeName: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.text,
      flexShrink: 1,
    },
    weekRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      flex: 1,
      paddingTop: 4,
      paddingBottom: 4,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    dayCell: {
      flex: 1,
      paddingHorizontal: 2,
      height: '100%',
    },
    dayHeader: {
      alignItems: 'center',
      marginBottom: 3,
    },
    dayNumberWrapper: {
      width: 26,
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayNumber: {
      fontSize: 13,
      color: theme.text,
    },
    dayNumberMuted: {
      color: theme.muted,
    },
    dayNumberSunday: {
      color: '#e04b4b',
    },
    selectedDayCircle: {
      borderRadius: 13,
      backgroundColor: theme.tint,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayNumberSelected: {
      color: theme.onTint,
      fontWeight: '700',
    },
    todayRingCircle: {
      borderRadius: 13,
      borderWidth: 1.5,
      borderColor: theme.tint,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayNumberToday: {
      color: theme.tint,
      fontWeight: '700',
    },
    eventStack: {
      gap: 4,
    },
    eventPill: {
      borderRadius: 6,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    eventText: {
      fontSize: 10,
      fontWeight: '600',
    },
    morePill: {
      alignSelf: 'flex-start',
      borderRadius: 6,
      paddingHorizontal: 6,
      paddingVertical: 2,
      backgroundColor: theme.border,
    },
    moreText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.muted,
    },
    weekPager: {
      flex: 1,
    },
    weekAgendaPage: {
      justifyContent: 'space-between',
    },
    weekAgendaDay: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      paddingVertical: 6,
    },
    weekAgendaDateCol: {
      width: 86,
      alignItems: 'center',
      justifyContent: 'center',
    },
    weekAgendaDate: {
      fontSize: 34,
      lineHeight: 36,
      fontWeight: '700',
      color: theme.text,
    },
    weekAgendaWeekday: {
      marginTop: 2,
      fontSize: 11,
      color: theme.muted,
      textTransform: 'capitalize',
    },
    weekAgendaEvents: {
      flex: 1,
      maxHeight: '100%',
      paddingRight: 8,
    },
    weekAgendaEventRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 4,
    },
    weekAgendaColorBar: {
      width: 4,
      height: 16,
      borderRadius: 2,
      marginRight: 6,
    },
    weekAgendaTime: {
      width: 44,
      fontSize: 11,
      lineHeight: 13,
      marginRight: 2,
      fontWeight: '600',
    },
    weekAgendaTitle: {
      flexShrink: 1,
      fontSize: 11,
      lineHeight: 13,
      color: theme.text,
      fontWeight: '600',
      marginRight: 2,
    },
    listContent: {
      paddingTop: 4,
      paddingBottom: 120,
    },
    listEmptyContent: {
      flexGrow: 1,
    },
    weekAgendaEmpty: {
      flex: 1,
      justifyContent: 'center',
      paddingRight: 8,
    },
    listLoadingFooter: {
      height: 56,
      alignItems: 'center',
      justifyContent: 'center',
    },
    listFullBleed: {
      marginHorizontal: -16,
    },
    listStickyHeader: {
      backgroundColor: theme.surface,
      borderTopWidth: 1,
      borderTopColor: theme.border,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    listStickyTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.text,
    },
    listStickyToday: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.muted,
    },
    listEventRow: {
      backgroundColor: theme.background,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 4,
    },
    listEventTimeCol: {
      width: 48,
      marginRight: 6,
    },
    listEventTime: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.text,
    },
    listEventTimeMuted: {
      marginTop: 1,
      fontSize: 10,
      color: theme.muted,
    },
    listEventBar: {
      width: 3,
      height: 36,
      borderRadius: 2,
      marginRight: 8,
    },
    listEventPhaseBar: {
      marginRight: 8,
    },
    listEventTextCol: {
      flex: 1,
    },
    listEventTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.text,
    },
    listEventSubtitle: {
      marginTop: 1,
      fontSize: 11,
      color: theme.muted,
    },
    listEventAvatar: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#d8cfc6',
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 6,
    },
    listEventAvatarText: {
      fontSize: 9,
      fontWeight: '700',
      color: '#4a4a4a',
    },
    menuOverlay: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
    },
    modeMenu: {
      position: 'absolute',
      backgroundColor: theme.surface,
      borderRadius: 18,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      shadowColor: '#000000',
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
    modeItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
    },
    modeItemActive: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
    },
    modeText: {
      flex: 1,
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
    },
    stateContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      paddingHorizontal: 32,
    },
    stateText: {
      fontSize: 15,
      color: theme.muted,
      textAlign: 'center',
    },
    retryButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: theme.tint,
    },
    retryButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.onTint,
    },
    errorBanner: {
      marginTop: 8,
      marginBottom: 4,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: '#fdecea',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    errorBannerText: {
      flex: 1,
      fontSize: 13,
      color: '#c0392b',
    },
    errorBannerRetry: {
      fontSize: 13,
      fontWeight: '700',
      color: '#c0392b',
    },
    staffMenu: {
      position: 'absolute',
      maxHeight: 320,
      backgroundColor: theme.surface,
      borderRadius: 18,
      paddingVertical: 6,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      shadowColor: '#000000',
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
    staffMenuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    staffMenuAvatar: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: '#d8cfc6',
      alignItems: 'center',
      justifyContent: 'center',
    },
    staffMenuName: {
      flex: 1,
      fontSize: 15,
      color: theme.text,
    },
  });
